# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    paths:
      - '**.js'
  pull_request:
    branches: [ $default-branch ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    - run: sudo apt-get install -y build-essential libgl1-mesa-dri libglapi-mesa
                                   libglew-dev libglu1-mesa-dev libosmesa6
                                   libxi-dev mesa-utils pkg-config
    - run: npm ci
    - run: npm run lint
    #- run: npm run build --if-present
    - run: npm run test
